# -*- coding: utf-8 -*-
"""lat_lon_to_healpix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzTyeNFiy-7RNY6UtGKsmDavX5dk6epU

# HealPIX regridding
Noah D. Brenowitz, Jan 22, 2024

In this notebook, I demonstrate bilinear regridding onto healpy grids in O(10)
ms. this is a 3 order of magnitude speed-up compared to what Dale has reported.

Now, lets define a healpix grid with indexing in the XY convention. we convert
to NEST indexing in order to use the `healpy.pix2ang` to get the lat lon
coordinates. This operation is near instant.
"""
# %%
import earth2grid

grid = earth2grid.healpix.Grid(level=4)
pv_grid = grid.to_pyvista()
pv_grid.plot(show_edges=True)
