name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y make
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Install pre-commit hooks
      run: |
        pre-commit install

    - name: Run lint
      run: |
        make lint
  build:

    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build package
      run: |
        apt-get update && apt-get install -y build-essential
        python -m pip install --upgrade pip
        pip install --no-build-isolation .
    - name: Run tests
      run: make unittest
    - name: coverage
      run: make coverage
