name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get install -y build-essential
    - name: lint
      run: make lint
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install --no-build-isolation .
        apt-get install -y build-essential
    - name: Run tests
      run: make unittest
    - name: coverage
      run: make coverage
